# Generated by Django 5.0.1 on 2024-03-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pet_percentage_pet_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='subtotal',
            new_name='price_and_Qunatity',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='total',
        ),
    ]
