# Generated by Django 5.0.1 on 2024-03-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pet_total_alter_customer_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
