# Generated by Django 5.0.1 on 2024-03-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_price_and_quantity_total_pet_price_and_quantity_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
